variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
    - mkdir public
    - cp -r _b4shl1b.sh public/_b4shl1b.sh
    - cp -r _b4shl1b.sh public/_init.sh
  artifacts:
    paths:
    - public
  only:
  - master
